micronaut:
  server:
    port: 8082
  application:
    name: subscriptionMicroservice
datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
    url: jdbc:mariadb://db/sm
    username: sm
    password: smsecret
jpa:
  default:
    entity-scan:
      packages:
        - uk.ac.york.eng2.sm.domains
    properties:
      hibernate:
        hbm2ddl:
          auto: update
netty:
  default:
    allocator:
      max-order: 3
kafka:
  #  enabled: false
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:`localhost:9094`}