CREATE DATABASE IF NOT EXISTS vm;
CREATE USER IF NOT EXISTS 'vm'@'%' IDENTIFIED BY 'vmsecret';
GRANT ALL PRIVILEGES ON vm.* TO 'vm'@'%';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS thm;
CREATE USER IF NOT EXISTS 'thm'@'%' IDENTIFIED BY 'thmsecret';
GRANT ALL PRIVILEGES ON thm.* TO 'thm'@'%';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS sm;
CREATE USER IF NOT EXISTS 'sm'@'%' IDENTIFIED BY 'smsecret';
GRANT ALL PRIVILEGES ON sm.* TO 'sm'@'%';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS hrm;
CREATE USER IF NOT EXISTS 'hrm'@'%' IDENTIFIED BY 'hrmsecret';
GRANT ALL PRIVILEGES ON hrm.* TO 'hrm'@'%';
FLUSH PRIVILEGES;
