micronaut:
  server:
    port: 8083
  application:
    name: recommendationMicroservice
datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
    url: jdbc:mariadb://localhost:3306/hrm
    username: hrm
    password: hrmsecret
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    entity-scan:
      packages:
        - uk.ac.york.eng2.hrm.domains
    properties:
      hibernate:
        hbm2ddl:
          auto: update
kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:`localhost:9094`}
