micronaut:
  server:
    port: 8081
  application:
    name: trendingHashtagMicroservice
datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
    url: jdbc:mariadb://localhost:3306/thm
    username: thm
    password: thmsecret
jpa:
  default:
    entity-scan:
      packages:
        - uk.ac.york.eng2.thm.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
netty:
  default:
    allocator:
      max-order: 3
kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:`localhost:9094`}
