micronaut:
  server:
    port: 8080
  application:
    name: videoMicroservice
datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
    url: jdbc:mariadb://db/vm
    username: vm
    password: vmsecret
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    entity-scan:
      packages:
        - uk.ac.york.eng2.vm.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
kafka:
#  enabled: false
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:`localhost:9094`}
